/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoseidonHasher,
  IPoseidonHasherInterface,
} from "../../../contracts/interfaces/IPoseidonHasher";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[1]",
        name: "inputs",
        type: "uint256[1]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoseidonHasher__factory {
  static readonly abi = _abi;
  static createInterface(): IPoseidonHasherInterface {
    return new utils.Interface(_abi) as IPoseidonHasherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoseidonHasher {
    return new Contract(address, _abi, signerOrProvider) as IPoseidonHasher;
  }
}
