/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISocialRecoveryVerifier,
  ISocialRecoveryVerifierInterface,
} from "../../../contracts/interfaces/ISocialRecoveryVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[3]",
        name: "input",
        type: "uint256[3]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "r",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISocialRecoveryVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ISocialRecoveryVerifierInterface {
    return new utils.Interface(_abi) as ISocialRecoveryVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISocialRecoveryVerifier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISocialRecoveryVerifier;
  }
}
