/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CheckBalanceInterface extends utils.Interface {
  functions: {
    "checkEthers(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "checkEthers"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkEthers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkEthers",
    data: BytesLike
  ): Result;

  events: {
    "CheckedBalance(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CheckedBalance"): EventFragment;
}

export interface CheckedBalanceEventObject {
  account: string;
  balanceRequired: BigNumber;
}
export type CheckedBalanceEvent = TypedEvent<
  [string, BigNumber],
  CheckedBalanceEventObject
>;

export type CheckedBalanceEventFilter = TypedEventFilter<CheckedBalanceEvent>;

export interface CheckBalance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CheckBalanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkEthers(
      balanceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  checkEthers(
    balanceRequired: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkEthers(
      balanceRequired: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CheckedBalance(address,uint256)"(
      account?: null,
      balanceRequired?: null
    ): CheckedBalanceEventFilter;
    CheckedBalance(
      account?: null,
      balanceRequired?: null
    ): CheckedBalanceEventFilter;
  };

  estimateGas: {
    checkEthers(
      balanceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkEthers(
      balanceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
